version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "RECONSTRUIRE"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    expose:
      - "5432"
    ports:
      - "3002:5432"
    volumes:
      # So that our database's state is persisted locally
      - ./postgres-dump:/docker-entrypoint-initdb.d
      # Where our data will be persisted
      - my-db:/var/lib/posgresql

# Names our volume
volumes:
  my-db:
